# fly.toml app configuration file generated for grupo-proteccion-ambiental on 2023-05-21T00:15:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grupo-proteccion-ambiental"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
