# Generated by Django 4.2.1 on 2023-05-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfpOnp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('commision', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='comision')),
                ('prima', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='prima')),
                ('mandatory', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='obligatorio')),
                ('is_onp', models.DecimalField(decimal_places=2, default=False, max_digits=6, verbose_name='es onp')),
            ],
            options={
                'verbose_name': 'AFP/ONP',
                'verbose_name_plural': 'AFPs/ONP',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(unique=True, verbose_name='es principal')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('ruc', models.CharField(max_length=200, verbose_name='ruc')),
                ('address', models.CharField(max_length=200, verbose_name='dirección')),
                ('signer_name', models.CharField(max_length=200, verbose_name='nombre del firmador')),
                ('signer_title', models.CharField(max_length=200, verbose_name='cargo del firmador')),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_children', models.BooleanField(default=False, verbose_name='tiene hijos')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salario')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco donde se le paga')),
                ('bank_account_number', models.CharField(max_length=100, verbose_name='Número de cuenta')),
                ('bank_account_number_cci', models.CharField(max_length=100, verbose_name='Número de cuenta interbancario')),
                ('afp_onp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.afponp', verbose_name='AFP/ONP')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ('person__name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='dni')),
                ('name', models.CharField(max_length=50, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellidos')),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'femenino'), (1, 'masculino')], null=True, verbose_name='sexo')),
                ('title', models.IntegerField(blank=True, choices=[(0, 'tec.'), (1, 'mvz.')], null=True, verbose_name='titulo')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('days_worked', models.IntegerField()),
                ('days_lazy', models.IntegerField()),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employ', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'boleta',
                'verbose_name_plural': 'boletas',
                'ordering': ('employ__person__name',),
            },
        ),
        migrations.AddField(
            model_name='employ',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='persona'),
        ),
        migrations.CreateModel(
            name='Dayli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at_1', models.DateTimeField(verbose_name='entrada 1')),
                ('end_at_1', models.DateTimeField(verbose_name='salida 1')),
                ('start_at_2', models.DateTimeField(blank=True, null=True, verbose_name='entrada 2')),
                ('end_at_2', models.DateTimeField(blank=True, null=True, verbose_name='salida 2')),
                ('hn', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='horas normales')),
                ('hn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='importe horas normales')),
                ('h25', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='horas al 25%')),
                ('h25_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='importe horas al 25%')),
                ('h35', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='horas al 35%')),
                ('h35_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='importe horas al 35%')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='importe')),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employ', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ('employ__person__name',),
            },
        ),
    ]
